2017-06-19 10:30:11 nao foi possivel procesasr a listagem para (nao possi configuracao de rsi) 12
2017-06-19 10:30:11 nao foi possivel procesasr a listagem para (nao possi configuracao de rsi) 38
2017-06-19 10:30:11 nao foi processado o rsi para (indices invalidos) 61
2017-06-19 10:30:11 nao foi processado o rsi para (indices invalidos) 98
2017-06-19 10:30:11 Sucesso insercao:  18
2017-06-19 10:30:11 Falha insercao:  0
